using System.IO;
using System.Text;
using System.Collections.Generic;

namespace MCLauncher.Services;

public enum ServerCoreType
{
    Purpur,
    Paper,
    Bukkit,
    Vanilla,
    Fabric,
    Forge
}

public class FileInfoItem
{
    public string Name = "";
    public string Type = "";
    public string Size = "";
    public string FullName = "";
}

public static class ServerCoreExtensions
{
    public static string Display(this ServerCoreType type) => type switch
    {
        ServerCoreType.Purpur => "Purpur",
        ServerCoreType.Paper => "Paper",
        ServerCoreType.Bukkit => "Bukkit",
        ServerCoreType.Vanilla => "Vanilla",
        ServerCoreType.Fabric => "Fabric",
        ServerCoreType.Forge => "Forge",
        _ => type.ToString()
    };

    public static string Description(this ServerCoreType type) => type switch
    {
        ServerCoreType.Purpur => "Высокопроизводительное ядро с оптимизациями",
        ServerCoreType.Paper => "Стабильное ядро с поддержкой плагинов",
        ServerCoreType.Bukkit => "Классическое ядро для плагинов",
        ServerCoreType.Vanilla => "Официальное ядро Mojang",
        ServerCoreType.Fabric => "Легковесное ядро для модов",
        ServerCoreType.Forge => "Популярное ядро для модов",
        _ => ""
    };
}

public class ServerConfig
{
    public string ServerName { get; set; } = "Minecraft Server";
    public ServerCoreType CoreType { get; set; } = ServerCoreType.Paper;
    public string McVersion { get; set; } = "1.20.4";
    public int MaxMemoryMb { get; set; } = 2048;
    public int MinMemoryMb { get; set; } = 512;
    public int Port { get; set; } = 25565;
    public bool OnlineMode { get; set; } = false;
    public string Motd { get; set; } = "A Minecraft Server";
    public int MaxPlayers { get; set; } = 20;
    public bool EnableUpnp { get; set; } = true;
    public bool EnableTunnel { get; set; } = true;
    public string? TunnelToken { get; set; }
    public string CustomJavaPath { get; set; } = "";

    private static string ServerDir => Path.Combine(LauncherPaths.Root, "server");
    private static string PropsFile => Path.Combine(ServerDir, "server.properties");
    private static string EulaFile => Path.Combine(ServerDir, "eula.txt");

    public static string GetServerDir() => ServerDir;
    public static string GetCoreJar() => Path.Combine(ServerDir, "server.jar");
    public static string GetPluginsDir() => Path.Combine(ServerDir, "plugins");

    public void EnsureServerDir()
    {
        Directory.CreateDirectory(ServerDir);
        Directory.CreateDirectory(GetPluginsDir());
    }

    public void WriteEula()
    {
        File.WriteAllText(EulaFile, "# Generated by MaysLauncher\r\neula=true\r\n", Encoding.UTF8);
    }

    public void WriteProperties()
    {
        var props = new Dictionary<string, string>
        {
            ["server-port"] = Port.ToString(),
            ["max-players"] = MaxPlayers.ToString(),
            ["online-mode"] = OnlineMode.ToString().ToLower(),
            ["motd"] = Motd,
            ["enable-command-block"] = "true",
            ["spawn-protection"] = "0",
            ["view-distance"] = "10",
            ["simulation-distance"] = "10",
            ["level-name"] = "world",
            ["level-seed"] = "",
            ["gamemode"] = "survival",
            ["difficulty"] = "normal",
            ["pvp"] = "true",
            ["white-list"] = "false",
            ["enforce-whitelist"] = "false"
        };

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by MaysLauncher");
        sb.AppendLine($"# {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        foreach (var kv in props)
            sb.AppendLine($"{kv.Key}={kv.Value}");

        File.WriteAllText(PropsFile, sb.ToString(), Encoding.UTF8);
    }

    public static ServerConfig Load()
    {
        var config = new ServerConfig();
        var configFile = Path.Combine(ServerDir, "server-config.json");
        try
        {
            if (File.Exists(configFile))
            {
                var json = File.ReadAllText(configFile);
                return System.Text.Json.JsonSerializer.Deserialize<ServerConfig>(json) ?? config;
            }
        }
        catch { }
        return config;
    }

    public void Save()
    {
        var configFile = Path.Combine(ServerDir, "server-config.json");
        try
        {
            File.WriteAllText(configFile, System.Text.Json.JsonSerializer.Serialize(this, new System.Text.Json.JsonSerializerOptions { WriteIndented = true }));
        }
        catch { }
    }
}
